#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EditorCommand {
    File(FileCommand),
    Edit(EditCommand),
    Window(WindowCommand),
    App(AppCommand),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FileCommand {
    New,
    Open,
    SwitchBuffer,
    Save,
    SaveAs,
    Reload,
    Close,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EditCommand {
    Undo,
    Redo,
    Cut,
    Copy,
    CopyExternal,
    Paste,
    SelectAll,
    SelectLine,
    CopyLine,
    DeleteLine,
    MoveLineUp,
    MoveLineDown,
    IndentLine,
    OutdentLine,
    TrimTrailingWhitespace,
    ToggleWordWrap,
    ToggleVisibleWhitespace,
    ToggleBookmark,
    NextBookmark,
    PreviousBookmark,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    MovePageUp,
    MovePageDown,
    MoveDocumentStart,
    MoveDocumentEnd,
    ScrollLeft,
    ScrollRight,
    MoveWordLeft,
    MoveWordRight,
    MoveLineStart,
    MoveLineEnd,
    ExtendSelectionPageUp,
    ExtendSelectionPageDown,
    ExtendSelectionWordLeft,
    ExtendSelectionWordRight,
    InsertNewline,
    DeleteBackward,
    DeleteForward,
    DeleteWordBackward,
    DeleteWordForward,
    Find,
    FindNext,
    FindPrevious,
    Replace,
    GoToLine,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum WindowCommand {
    SplitHorizontal,
    SplitVertical,
    FocusLeft,
    FocusRight,
    FocusUp,
    FocusDown,
    ResizeLeft,
    ResizeRight,
    ResizeUp,
    ResizeDown,
    Equalize,
    RotateSplit,
    Collapse,
    Expand,
    ToggleCollapse,
    Close,
    Only,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AppCommand {
    CommandLine,
    ConfigDiagnostics,
    Help,
    ReloadConfig,
    RunCommand,
    CommandOutputClear,
    CommandOutputCopy,
    CommandOutputIndex,
    CommandOutputNextMatch,
    CommandOutputPreviousMatch,
    CommandOutputStderr,
    CommandOutputStderrBody,
    CommandOutputStatus,
    CommandOutputStdout,
    CommandOutputStdoutBody,
    CommandOutputSummary,
    CommandOutputSave,
    CommandOutputTruncated,
    ConfigDiagnosticsClipboard,
    ConfigDiagnosticsFileDialogKeymap,
    ConfigDiagnosticsInput,
    ConfigDiagnosticsKeymap,
    ConfigDiagnosticsLimits,
    ConfigDiagnosticsPaths,
    ConfigDiagnosticsSource,
    ConfigDiagnosticsSummary,
    ConfigDiagnosticsTerminal,
    ShellEscape,
    StatusHistory,
    Quit,
}
