[workspace]
resolver = "3"
members = [
    "crates/dun-cli",
    "crates/dun-config",
    "crates/dun-core",
    "crates/dun-term",
    "crates/dun-ui",
]
default-members = ["crates/dun-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[workspace.dependencies]
crossterm = "0.28"
dun-config = { path = "crates/dun-config" }
dun-core = { path = "crates/dun-core" }
dun-term = { path = "crates/dun-term" }
dun-ui = { path = "crates/dun-ui" }
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
unicode-width = "0.2"
