[workspace]
resolver = "3"
members = [
    "crates/dun-cli",
    "crates/dun-config",
    "crates/dun-core",
    "crates/dun-plugin",
    "crates/dun-term",
    "crates/dun-ui",
]
default-members = ["crates/dun-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[workspace.dependencies]
crossterm = "0.28"
dun-config = { path = "crates/dun-config" }
dun-core = { path = "crates/dun-core" }
dun-plugin = { path = "crates/dun-plugin" }
dun-term = { path = "crates/dun-term" }
dun-ui = { path = "crates/dun-ui" }
rustix = { version = "0.38", default-features = false, features = ["std", "stdio", "termios", "event"] }
unicode-width = "0.2"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
