[package]
name = "dun-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Host-neutral Dun Plugin Protocol client."

[dependencies]
rustix.workspace = true
