#!/usr/bin/env bash
# Launch dun deterministically for the real-terminal acceptance checklist and
# the gallery-screenshot pass (docs/real-terminal-acceptance.md).
#
# It writes a throwaway config to a scratch dir and points dun at it with
# DUN_CONFIG, so your real ~/.config/dun is never touched. It opens the
# committed acceptance fixture. Resize the terminal window to the size the
# checklist item asks for (usually 80x24) BEFORE reading the result.
#
# Usage:
#   acceptance/launch.sh [theme] [flags]
#     theme            dun (default) | msedit | dark | turbo
#   flags (repeatable, any order):
#     --osc52-write    clipboard.osc52.enabled = true   (edit.copy_external)
#     --osc52-read     clipboard.osc52.allow_read = true (edit.paste_external)
#     --mouse          mouse.enabled = true
#     --ascii          terminal.encoding = ascii
#     --16color        terminal.colors = 16
#     --mono           terminal.colors = mono
#     --file PATH      open PATH instead of the default fixture
#
# Examples:
#   acceptance/launch.sh msedit --mouse
#   acceptance/launch.sh dun --osc52-read --osc52-write
#   NO_COLOR=1 acceptance/launch.sh dun     # capability-fallback mono path
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
theme="dun"
file="$repo_root/acceptance/fixture.txt"
osc52_write="false"
osc52_read="false"
mouse="false"
encoding="utf8"
colors="256"

while [ $# -gt 0 ]; do
    case "$1" in
        dun|msedit|dark|turbo) theme="$1" ;;
        --osc52-write) osc52_write="true" ;;
        --osc52-read) osc52_read="true" ;;
        --mouse) mouse="true" ;;
        --ascii) encoding="ascii" ;;
        --16color) colors="16" ;;
        --mono) colors="mono" ;;
        --file) shift; file="$1" ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
    shift
done

# Prefer the size-budget build; fall back to a plain release build; build if neither exists.
bin=""
for candidate in \
    "$repo_root/target/x86_64-apple-darwin/release/dun" \
    "$repo_root/target/aarch64-apple-darwin/release/dun" \
    "$repo_root/target/release/dun"; do
    if [ -x "$candidate" ]; then bin="$candidate"; break; fi
done
if [ -z "$bin" ]; then
    echo "no dun binary found; building (cargo build --release)..." >&2
    ( cd "$repo_root" && cargo build --release >&2 )
    bin="$repo_root/target/release/dun"
fi

scratch="$(mktemp -d "${TMPDIR:-/tmp}/dun-acceptance.XXXXXX")"
config="$scratch/config"
cat > "$config" <<EOF
# Generated by acceptance/launch.sh — throwaway config, safe to delete.
theme = $theme
terminal.encoding = $encoding
terminal.colors = $colors
mouse.enabled = $mouse
clipboard.osc52.enabled = $osc52_write
clipboard.osc52.allow_read = $osc52_read
EOF

echo "dun    : $bin" >&2
echo "config : $config (theme=$theme encoding=$encoding colors=$colors mouse=$mouse osc52_write=$osc52_write osc52_read=$osc52_read)" >&2
echo "file   : $file" >&2
echo "(resize the window as the checklist item asks, then interact)" >&2

DUN_CONFIG="$config" "$bin" "$file"
status=$?
rm -rf "$scratch"
exit $status
