use super::Style;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Palette {
    pub editor: Style,
    pub editor_text: Style,
    pub menu_bar: Style,
    pub menu_text: Style,
    pub menu_hotkey: Style,
    pub menu_active: Style,
    pub menu_active_hotkey: Style,
    pub menu_panel: Style,
    pub menu_panel_text: Style,
    pub menu_panel_hotkey: Style,
    pub menu_panel_border: Style,
    pub status_bar: Style,
    pub status_text: Style,
    pub window_border: Style,
    pub window_border_focused: Style,
    pub title: Style,
    pub title_focused: Style,
    pub gutter: Style,
    pub gutter_separator: Style,
    pub current_line: Style,
    pub selection: Style,
    pub selection_text: Style,
    pub search_match: Style,
    pub active_search_match: Style,
    pub scrollbar_thumb: Style,
    pub modal_scrim: Style,
    pub modal: Style,
    pub modal_text: Style,
    pub modal_border: Style,
    pub modal_input: Style,
    pub dirty: Style,
    pub read_only: Style,
    pub control: Style,
    pub escape: Style,
    pub truncation: Style,
    pub syntax_keyword: Style,
    pub syntax_comment: Style,
    pub syntax_string: Style,
    pub syntax_number: Style,
    pub syntax_emphasis: Style,
    pub warning: Style,
}

impl Palette {
    pub fn role(&self, id: &str) -> Option<Style> {
        Some(match id {
            "editor" => self.editor,
            "editor_text" => self.editor_text,
            "menu_bar" => self.menu_bar,
            "menu_text" => self.menu_text,
            "menu_hotkey" => self.menu_hotkey,
            "menu_active" => self.menu_active,
            "menu_active_hotkey" => self.menu_active_hotkey,
            "menu_panel" => self.menu_panel,
            "menu_panel_text" => self.menu_panel_text,
            "menu_panel_hotkey" => self.menu_panel_hotkey,
            "menu_panel_border" => self.menu_panel_border,
            "status_bar" => self.status_bar,
            "status_text" => self.status_text,
            "window_border" => self.window_border,
            "window_border_focused" => self.window_border_focused,
            "title" => self.title,
            "title_focused" => self.title_focused,
            "gutter" => self.gutter,
            "gutter_separator" => self.gutter_separator,
            "current_line" => self.current_line,
            "selection" => self.selection,
            "selection_text" => self.selection_text,
            "search_match" => self.search_match,
            "active_search_match" => self.active_search_match,
            "scrollbar_thumb" => self.scrollbar_thumb,
            "modal_scrim" => self.modal_scrim,
            "modal" => self.modal,
            "modal_text" => self.modal_text,
            "modal_border" => self.modal_border,
            "modal_input" => self.modal_input,
            "dirty" => self.dirty,
            "read_only" => self.read_only,
            "control" => self.control,
            "escape" => self.escape,
            "truncation" => self.truncation,
            "syntax_keyword" => self.syntax_keyword,
            "syntax_comment" => self.syntax_comment,
            "syntax_string" => self.syntax_string,
            "syntax_number" => self.syntax_number,
            "syntax_emphasis" => self.syntax_emphasis,
            "warning" => self.warning,
            _ => return None,
        })
    }

    pub fn role_mut(&mut self, id: &str) -> Option<&mut Style> {
        Some(match id {
            "editor" => &mut self.editor,
            "editor_text" => &mut self.editor_text,
            "menu_bar" => &mut self.menu_bar,
            "menu_text" => &mut self.menu_text,
            "menu_hotkey" => &mut self.menu_hotkey,
            "menu_active" => &mut self.menu_active,
            "menu_active_hotkey" => &mut self.menu_active_hotkey,
            "menu_panel" => &mut self.menu_panel,
            "menu_panel_text" => &mut self.menu_panel_text,
            "menu_panel_hotkey" => &mut self.menu_panel_hotkey,
            "menu_panel_border" => &mut self.menu_panel_border,
            "status_bar" => &mut self.status_bar,
            "status_text" => &mut self.status_text,
            "window_border" => &mut self.window_border,
            "window_border_focused" => &mut self.window_border_focused,
            "title" => &mut self.title,
            "title_focused" => &mut self.title_focused,
            "gutter" => &mut self.gutter,
            "gutter_separator" => &mut self.gutter_separator,
            "current_line" => &mut self.current_line,
            "selection" => &mut self.selection,
            "selection_text" => &mut self.selection_text,
            "search_match" => &mut self.search_match,
            "active_search_match" => &mut self.active_search_match,
            "scrollbar_thumb" => &mut self.scrollbar_thumb,
            "modal_scrim" => &mut self.modal_scrim,
            "modal" => &mut self.modal,
            "modal_text" => &mut self.modal_text,
            "modal_border" => &mut self.modal_border,
            "modal_input" => &mut self.modal_input,
            "dirty" => &mut self.dirty,
            "read_only" => &mut self.read_only,
            "control" => &mut self.control,
            "escape" => &mut self.escape,
            "truncation" => &mut self.truncation,
            "syntax_keyword" => &mut self.syntax_keyword,
            "syntax_comment" => &mut self.syntax_comment,
            "syntax_string" => &mut self.syntax_string,
            "syntax_number" => &mut self.syntax_number,
            "syntax_emphasis" => &mut self.syntax_emphasis,
            "warning" => &mut self.warning,
            _ => return None,
        })
    }
}

pub const PALETTE_ROLE_IDS: &[&str] = &[
    "editor",
    "editor_text",
    "menu_bar",
    "menu_text",
    "menu_hotkey",
    "menu_active",
    "menu_active_hotkey",
    "menu_panel",
    "menu_panel_text",
    "menu_panel_hotkey",
    "menu_panel_border",
    "status_bar",
    "status_text",
    "window_border",
    "window_border_focused",
    "title",
    "title_focused",
    "gutter",
    "gutter_separator",
    "current_line",
    "selection",
    "selection_text",
    "search_match",
    "active_search_match",
    "scrollbar_thumb",
    "modal_scrim",
    "modal",
    "modal_text",
    "modal_border",
    "modal_input",
    "dirty",
    "read_only",
    "control",
    "escape",
    "truncation",
    "syntax_keyword",
    "syntax_comment",
    "syntax_string",
    "syntax_number",
    "syntax_emphasis",
    "warning",
];
