use super::Style;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Palette {
    pub editor: Style,
    pub editor_text: Style,
    pub menu_bar: Style,
    pub menu_text: Style,
    pub menu_hotkey: Style,
    pub menu_active: Style,
    pub menu_active_hotkey: Style,
    pub menu_panel: Style,
    pub menu_panel_text: Style,
    pub menu_panel_hotkey: Style,
    pub menu_panel_border: Style,
    pub status_bar: Style,
    pub status_text: Style,
    pub window_border: Style,
    pub window_border_focused: Style,
    pub title: Style,
    pub title_focused: Style,
    pub gutter: Style,
    pub gutter_separator: Style,
    pub current_line: Style,
    pub selection: Style,
    pub selection_text: Style,
    pub search_match: Style,
    pub active_search_match: Style,
    pub scrollbar_thumb: Style,
    pub modal_scrim: Style,
    pub modal: Style,
    pub modal_text: Style,
    pub modal_border: Style,
    pub modal_input: Style,
    pub dirty: Style,
    pub read_only: Style,
    pub control: Style,
    pub escape: Style,
    pub truncation: Style,
}
