[package]
name = "dun-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Command-line entry point for dun."

[[bin]]
name = "dun"
path = "src/main.rs"

[features]
test-panic-hook = []

[dependencies]
crossterm.workspace = true
dun-config.workspace = true
dun-core.workspace = true
dun-plugin.workspace = true
dun-term.workspace = true
dun-ui.workspace = true
mio.workspace = true
