[package]
name = "dun-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Command-line entry point for dun."

[[bin]]
name = "dun"
path = "src/main.rs"

[features]
test-panic-hook = []

[dependencies]
dun-config.workspace = true
dun-core.workspace = true
dun-plugin.workspace = true
dun-term.workspace = true
dun-ui.workspace = true
rustix.workspace = true
signal-hook.workspace = true
